
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package CodigoFases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 13;
  public static final int PARACADA = 6;
  public static final int MENORQ = 31;
  public static final int ENTERO = 41;
  public static final int SI = 23;
  public static final int FUNCION = 5;
  public static final int RESTA = 28;
  public static final int DESDE = 19;
  public static final int ENTONCES = 25;
  public static final int PUNTOCOMA = 35;
  public static final int DTAB = 43;
  public static final int INCREMENTAR = 22;
  public static final int PRINCIPAL = 11;
  public static final int ENCASO = 26;
  public static final int IGUAL = 33;
  public static final int SINO = 24;
  public static final int TAB = 42;
  public static final int MIENTRAS = 21;
  public static final int PARAB = 36;
  public static final int ESCRIBIR = 4;
  public static final int DIV = 30;
  public static final int CODIGO = 8;
  public static final int SUMA = 27;
  public static final int ITERAR = 20;
  public static final int ID = 40;
  public static final int EOF = 0;
  public static final int CLASE = 3;
  public static final int COMILLA = 39;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NULO = 14;
  public static final int CADENA = 12;
  public static final int BOLEANO = 16;
  public static final int PARCE = 37;
  public static final int PUNTO = 34;
  public static final int MAYORQ = 32;
  public static final int VARIABLE = 10;
  public static final int INCLUIR = 2;
  public static final int DPUNTO = 38;
  public static final int FALSO = 15;
  public static final int LEER = 9;
  public static final int HACER = 18;
  public static final int RETORNAR = 7;
  public static final int VERDADERO = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCLUIR",
  "CLASE",
  "ESCRIBIR",
  "FUNCION",
  "PARACADA",
  "RETORNAR",
  "CODIGO",
  "LEER",
  "VARIABLE",
  "PRINCIPAL",
  "CADENA",
  "NUMERO",
  "NULO",
  "FALSO",
  "BOLEANO",
  "VERDADERO",
  "HACER",
  "DESDE",
  "ITERAR",
  "MIENTRAS",
  "INCREMENTAR",
  "SI",
  "SINO",
  "ENTONCES",
  "ENCASO",
  "SUMA",
  "RESTA",
  "MUL",
  "DIV",
  "MENORQ",
  "MAYORQ",
  "IGUAL",
  "PUNTO",
  "PUNTOCOMA",
  "PARAB",
  "PARCE",
  "DPUNTO",
  "COMILLA",
  "ID",
  "ENTERO",
  "TAB",
  "DTAB"
  };
}

